#! /bin/sh

sxhkd &
~/.config/fehbg &
polybar example &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a emacs mode=tiled
