#! /bin/sh

$HOME/.config/bspwm/autostart.sh &
. "$HOME/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5 6

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config border_width 1
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
